### ISSUE TITLE
error in databasemanager

### ISSUE THREAD

**Issue by theyush** [BeepFelix/csgo-commend-bot#105]
I'm having this error :(

```

PS C:\Users\54\Desktop\CSGO-CommendBOT-2019-master> node databaseManager.js
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'C:\Users\54\Desktop\CSGO-CommendBOT-2019-master\node_modules\sqlite3\lib\binding\node-v64-win32-x64\node_sqlite3.node'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\54\Desktop\CSGO-CommendBOT-2019-master\node_modules\sqlite3\lib\sqlite3.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

**Comment by BeepFelix** [comment]
What is your NodeJS version? (`node -v`)

**Comment by theyush** [comment]
I am using this version 
v10.16.3

**Comment by BeepFelix** [comment]
Upgrade NodeJS

**Comment by theyush** [comment]
> Upgrade NodeJS

I am using the latest version

**Comment by BeepFelix** [comment]
Yes

**Comment by theyush** [comment]
thanks it's working now :)
