### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by JeeyM** [BeepFelix/csgo-commend-bot#11]
SyntaxError: Unexpected token (
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

**Comment by JeeyM** [comment]
The same issue

**Comment by BeepFelix** [comment]
What node version do you have? `node -v` in a command prompt

**Comment by JeeyM** [comment]
node.js 6.9.2

**Comment by Lines08** [comment]
V11.6.0

**Comment by BeepFelix** [comment]
@JeeyM Try updating your [NodeJS](https://nodejs.org/) version. 

@Lines08 Uhh, try downgrading to 10.15.0? What is your exact error message?

**Comment by JeeyM** [comment]
Working after update to 10.15.0, thanks for help!
