### ISSUE TITLE
Startup problem

### ISSUE THREAD

**Issue by Siezek1** [BeepFelix/csgo-commend-bot#111]
Hello
I have a problem running the program, I have already found in discussions how to fix this problem, but this does not work, I installed the latest version of node js and does not work anymore.

Error:
root@siezekminecra:/home/pochwaly# node index.js
/home/pochwaly/helpers/account.js:192
                                } catch { }
                                        ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pochwaly/index.js:8:17)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)

**Comment by BeepFelix** [comment]
Upgrade NodeJS.

As per requirements: `NodeJS v11 or later`

You installed LTS which is `v10.16.3`.

Install current.

**Comment by Siezek1** [comment]
Give me command pls

**Comment by BeepFelix** [comment]
Use your brain and google. Its all completely explained.

https://nodejs.org/en/download/package-manager/

Select your distro and follow the instructions.
