### ISSUE TITLE
proxy 

### ISSUE THREAD

**Issue by lowzin** [BeepFelix/csgo-commend-bot#25]
{ Error: connect ETIMEDOUT 93.99.179.133:8080
    at SteamUser._handleLogOff (C:\Users\Brend\OneDrive\bot\node_modules\steam-user\components\logon.js:400:11)
    at CMClient.<anonymous> (C:\Users\Brend\OneDrive\bot\node_modules\steam-user\index.js:124:8)
    at CMClient.emit (events.js:182:13)
    at TCPConnection.<anonymous> (C:\Users\Brend\OneDrive\bot\node_modules\steam-client\lib\cm_client.js:136:11)
    at ClientRequest.<anonymous> (C:\Users\Brend\OneDrive\bot\node_modules\steam-client\lib\tcp_connection.js:87:14)
    at ClientRequest.emit (events.js:182:13)
    at Socket.socketErrorListener (_http_client.js:392:9)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3) eresult: 35 }
[3KQD2THJE6ZF] Has encountered an error
{ Error: connect ETIMEDOUT 93.99.179.133:8080
    at SteamUser._handleLogOff (C:\Users\Brend\OneDrive\bot\node_modules\steam-user\components\logon.js:400:11)
    at CMClient.<anonymous> (C:\Users\Brend\OneDrive\bot\node_modules\steam-user\index.js:124:8)
    at CMClient.emit (events.js:182:13)
    at TCPConnection.<anonymous> (C:\Users\Brend\OneDrive\bot\node_modules\steam-client\lib\cm_client.js:136:11)
    at ClientRequest.<anonymous> (C:\Users\Brend\OneDrive\bot\node_modules\steam-client\lib\tcp_connection.js:87:14)
    at ClientRequest.emit (events.js:182:13)
    at Socket.socketErrorListener (_http_client.js:392:9)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3) eresult: 35 }

**Comment by BeepFelix** [comment]
Your proxy doesn't work or is blocked by Steam.
