### ISSUE TITLE
Syntax error 

### ISSUE THREAD

**Issue by janekaldo** [BeepFelix/csgo-commend-bot#29]
Debian 8

What am I doing wrong?

`janek@janekaldo:/var/csgo-commend-bot$ node index.js my_acc 1
/var/csgo-commend-bot/index.js:42
(async () => {
       ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)`

**Comment by janekaldo** [comment]
Thanks, I updated it with package manager to the latest version and now it works just fine.

Thanks for your fast support again.
