### ISSUE TITLE
problems

### ISSUE THREAD

**Issue by sorov97** [BeepFelix/csgo-commend-bot#36]
[SeparateToweringDeer] Has encountered an error
{ Error: read ECONNRESET
    at SteamUser._handleLogOff (C:\Users\U\Desktop\commend\node_modules\steam-user\components\logon.js:400:11)
    at CMClient.<anonymous> (C:\Users\U\Desktop\commend\node_modules\steam-user\index.js:124:8)
    at CMClient.emit (events.js:197:13)
    at TCPConnection.<anonymous> (C:\Users\U\Desktop\commend\node_modules\steam-client\lib\cm_client.js:136:11)
    at ClientRequest.<anonymous> (C:\Users\U\Desktop\commend\node_modules\steam-client\lib\tcp_connection.js:87:14)
    at ClientRequest.emit (events.js:197:13)
    at Socket.socketErrorListener (_http_client.js:399:9)
    at Socket.emit (events.js:197:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3) eresult: 35 }

always show this

**Comment by BeepFelix** [comment]
Proxy issue I assume.

Proxy blocked by Steam, Proxy unavailable, Proxy doesn't like multiple connections, Proxy unsupported, etc.

**Comment by sorov97** [comment]
> Proxy issue I assume.
> 
> Proxy blocked by Steam, Proxy unavailable, Proxy doesn't like multiple connections, Proxy unsupported, etc.

what proxy i can use, socks mb? and can u help with prefix
![image](https://user-images.githubusercontent.com/22113060/52198467-019e9c00-2874-11e9-81b8-7989a9979197.png)
and can i do smth like that with proxies?

**Comment by BeepFelix** [comment]
Yes. Make sure the last one doesn't have a comma.

**Comment by sorov97** [comment]
> Yes. Make sure the last one doesn't have a comma.

but what about prefix? what proxy can i use
no comma in end
![image](https://user-images.githubusercontent.com/22113060/52198547-47f3fb00-2874-11e9-85f6-ea219e3c0cab.png)

**Comment by BeepFelix** [comment]
Only HTTP

**Comment by sorov97** [comment]
> Only HTTP

where u take proxies? cause i use public(

**Comment by BeepFelix** [comment]
I don't use proxies.

**Comment by sorov97** [comment]
![image](https://user-images.githubusercontent.com/22113060/52198681-af11af80-2874-11e9-8e73-e61d7d9c38fb.png)
and now i have smth like this

**Comment by BeepFelix** [comment]
Public proxies are blocked by Steam

**Comment by sorov97** [comment]
> Public proxies are blocked by Steam

if i use checked proxy from december do u think are they blocked?

**Comment by sorov97** [comment]
sorry for spamming, cause i have 70k accs

**Comment by BeepFelix** [comment]
Steam blocks almost all Proxies you can find, even some paid ones
