### ISSUE TITLE
annoying timeout after commending once

### ISSUE THREAD

**Issue by w3bn00b** [BeepFelix/csgo-commend-bot#5]
i successfully commended my account but when i tried once again after 12 hours it doesnt work

```
Getting 2 accounts
Parsing account from STEAM_0:0:458937646
Successfully parsed account to 917875292
[ShinyInsidiousHornet] Logging into account
[IncompetentPinkGoldfinch] Logging into account
[ShinyInsidiousHornet] Successfully logged into account
[IncompetentPinkGoldfinch] Successfully logged into account
[ShinyInsidiousHornet] Connected to CSGO GameCoordinator
[IncompetentPinkGoldfinch] Connected to CSGO GameCoordinator
[ShinyInsidiousHornet] Has encountered an error
Error: Failed to send commend: Timeout
    at Timeout.setTimeout [as _onTimeout] (/home/kevinpark/csgo-commend-bot/helpers/account.js:128:12)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
[IncompetentPinkGoldfinch] Has encountered an error
Error: Failed to send commend: Timeout
    at Timeout.setTimeout [as _onTimeout] (/home/kevinpark/csgo-commend-bot/helpers/account.js:128:12)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
Successfully sent 0/2 commends, 2 commends failed
```

**Comment by ruwenj** [comment]
Same goes for me and every time after the 27th commend I'll get the Timeout message: https://i.imgur.com/WkaNZVP.png

**Comment by w3bn00b** [comment]
ofc I'm commending different account...
should i try with different accs?

**Comment by w3bn00b** [comment]
nvm it's working perfect now

**Comment by BeepFelix** [comment]
Timeouts should only happen when your internet connection is having issues or the GameCoordinator is having issues (See [steamstat.us](https://steamstat.us/)). Other than that I don't know why the GC would ignore our request.

It could be that you might have manually terminated the script and it didn't properly save the settings so it used the same accounts as previously to commend you.
