### ISSUE TITLE
Problem.

### ISSUE THREAD

**Issue by MikkelDK** [BeepFelix/csgo-commend-bot#7]
Hey @BeepFelix 

Dunno about you is active. ;) 

I got some issues.

```
Error: Failed to connect to GC: Timeout
    at Timeout._timeout.setTimeout [as _onTimeout] (/root/csgo-commend-bot-master/helpers/account.js:84:24)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
Successfully sent 0/5 commends, 5 commends failed
/root/csgo-commend-bot-master/node_modules/steam-client/lib/cm_client.js:241
        this._connection.send(Buffer.concat([header.toBuffer(), body]));
                         ^

TypeError: Cannot read property 'send' of undefined
    at CMClient._send (/root/csgo-commend-bot-master/node_modules/steam-client/lib/cm_client.js:241:19)
    at CMClient.send (/root/csgo-commend-bot-master/node_modules/steam-client/lib/cm_client.js:271:7)
    at SteamGameCoordinator._send (/root/csgo-commend-bot-master/node_modules/steam/lib/handlers/game_coordinator/index.js:49:16)
    at SteamGameCoordinator.send (/root/csgo-commend-bot-master/node_modules/steam/lib/handlers/game_coordinator/index.js:67:8)
    at Timeout._GCHelloInterval.setInterval [as _onTimeout] (/root/csgo-commend-bot-master/helpers/GameCoordinator.js:28:13)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)

```

**Comment by BeepFelix** [comment]
Timeouts just sometimes happen, don't really know why.

As for the crash, I had that before but don't really know why. Didn't investigate it further as it never happened again afterwards. Might try to take a look at it again during the weekend.

**Comment by MikkelDK** [comment]
Let me know, if you have a fix! ;) just weird, it's happens now with "Cannot read property 'send' " ;/

**Comment by BeepFelix** [comment]
Potential fix in: dc4852e0049cce34bb32fdf671fc8206c4de5908

It should prevent the script from crashing at least. Why it happens in the first place I don't really know. Please go ahead an test it out.

**Comment by MikkelDK** [comment]
hmm..

dunno why i'm getting this:
```
Error: Failed to send commend: Timeout
    at Timeout.setTimeout [as _onTimeout] (/root/csgo-commend-bot-master/helpers/account.js:137:12)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)

```

**Comment by MikkelDK** [comment]
`"CommendsPerChunk": 100,`

;)

**Comment by BeepFelix** [comment]
Hmm, I don't really know what else could cause it besides the ones listed above. I never had this issue before.

Verify that the part in `AccountToCommend` is a valid Steam User and that the accounts did not already commend within the past 12 hours.

Other than that, really no idea.

**Comment by MikkelDK** [comment]
Thanks for help, anyway! ;)
