### ISSUE TITLE
timeout error with serverID in "auto"

### ISSUE THREAD

**Issue by cazorlassj** [BeepFelix/csgo-commend-bot#73]
C:\g\csg>node index.js
 Checking for new update...
 Up to date!
 Checking protobufs...
 Found protobufs
 Opening database...
 There are a total of 1067 operational accounts
 Parsing target account...
 Chunking 1 account into groups of 20...
 Parsing server input
Error: Failed to send message: Timeout
    at Timeout._onTimeout (C:\g\csg\helpers\GameCoordinator.js:154:12)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7) Promise {
  <rejected> Error: Failed to send message: Timeout
      at Timeout._onTimeout (C:\g\csg\helpers\GameCoordinator.js:154:12)
      at listOnTimeout (internal/timers.js:531:17)
      at processTimers (internal/timers.js:475:7)
}

**Comment by LuxiDK** [comment]
I have same error right now.

**Comment by LuxiDK** [comment]
How did you get that many accounts? I'm trying to find some steam accounts with no games, but they're all taken already..

**Comment by BeepFelix** [comment]
`auto` is currently not working. I released this too soon, apologies. Just use the normal way until I figure this out. I don't know how long this will take.
