### ISSUE TITLE
Error: LoggedInElsewhere

### ISSUE THREAD

**Issue by urlykxz** [BeepFelix/csgo-commend-bot#91]
https://prnt.sc/p31dwn 
when this error occurs, it seems like the rest of the accounts just do not work and the next chunk goes. is it my way or all the same a mistake in the code

**Comment by BeepFelix** [comment]
What's your config?

**Comment by urlykxz** [comment]
{
	"commend": {
		"friendly": 140,
		"teaching": 140,
		"leader": 140
	},
	"account": {
		"username": "",
		"password": "",
		"sharedSecret": ""
	},
	"fetcher": {
		"username": "PrimeAccount",
		"password": "PrimePassword",
		"sharedSecret": "",
		"maxTries": 10,
		"tryDelay": 2500,
		"askSteamGuard": true
	},
	"method": "SERVER",
	"target": "https://steamcommunity.com/id/z-j-g/",
	"serverID": "[A:1:4170385408:13245]",
	"matchID": "0",
	"perChunk": 20,
	"betweenChunks": 300000,
	"cooldown": 28800000,
	"steamWebAPIKey": "9DF38455BDA4E3BADDFA38BAE60FA23A"
}

**Comment by BeepFelix** [comment]
I don't know why this could happen. It shouldn't happen, it *can't* happen. Either: Steam reports the wrong error code *or* the script sometimes selects the same account? I never had it happen myself. I don't know how to replicate it.

**Comment by urlykxz** [comment]
events.js:186
      throw er; // Unhandled 'error' event
      ^

Error: LoggedInElsewhere
    at SteamUser._handleLogOff (E:\Users\546\Desktop\csgo-commend-bot-master\node_modules\steam-user\components\logon.js:500:11)
    at SteamUser.<anonymous> (E:\Users\546\Desktop\csgo-commend-bot-master\node_modules\steam-user\components\logon.js:471:7)
    at E:\Users\546\Desktop\csgo-commend-bot-master\node_modules\steam-user\components\classes\HandlerManager.js:37:12
    at Array.forEach (<anonymous>)
    at HandlerManager.emit (E:\Users\546\Desktop\csgo-commend-bot-master\node_modules\steam-user\components\classes\HandlerManager.js:36:12)
    at SteamUser._handleMessage (E:\Users\546\Desktop\csgo-commend-bot-master\node_modules\steam-user\components\messages.js:532:24)
    at SteamUser._handleNetMessage (E:\Users\546\Desktop\csgo-commend-bot-master\node_modules\steam-user\components\messages.js:467:7)
    at SteamUser.processMulti (E:\Users\546\Desktop\csgo-commend-bot-master\node_modules\steam-user\components\messages.js:559:9)
    at SteamUser.<anonymous> (E:\Users\546\Desktop\csgo-commend-bot-master\node_modules\steam-user\components\messages.js:553:16)
    at E:\Users\546\Desktop\csgo-commend-bot-master\node_modules\steam-user\components\classes\HandlerManager.js:37:12
Emitted 'error' event on SteamUser instance at:
    at SteamUser._handleLogOff (E:\Users\546\Desktop\csgo-commend-bot-master\node_modules\steam-user\components\logon.js:507:8)
    at SteamUser.<anonymous> (E:\Users\546\Desktop\csgo-commend-bot-master\node_modules\steam-user\components\logon.js:471:7)
    [... lines matching original stack trace ...]
    at E:\Users\546\Desktop\csgo-commend-bot-master\node_modules\steam-user\components\classes\HandlerManager.js:37:12 {
  eresult: 6

maybe there are errors in this code?

**Comment by BeepFelix** [comment]
There are not, else it would always happen. It doesn't always happen.

**Comment by urlykxz** [comment]
one solution how to fix this is to delete accounts that someone has visited?

**Comment by BeepFelix** [comment]
That makes no sense. The accounts are **not** used, yet Steam says it failed to login.

**Comment by BeepFelix** [comment]
Closing in favor of #90
