### ISSUE TITLE
Error when starting

### ISSUE THREAD

**Issue by markbmullins** [BeepFelix/csgo-commend-bot#94]
```
/csgo-commend-bot/helpers/account.js:180
                                } catch { }
                                        ^

SyntaxError: Unexpected token {
    at new Script (vm.js:51:7)
    at createScript (vm.js:136:10)
    at Object.runInThisContext (vm.js:197:10)
    at Module._compile (internal/modules/cjs/loader.js:618:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (/Users/markmullins/Documents/code/csgo-commend-bot/index.js:8:17)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
```

**Comment by BeepFelix** [comment]
Update NodeJS

**Comment by markbmullins** [comment]
That worked thanks.

**Comment by markbmullins** [comment]
@BeepFelix unrelated, do you have a way to get many sets of credentials for the bot?

**Comment by BeepFelix** [comment]
No
